
        vars: { 
            d2-config: { 
                layout-engine: elk 
                theme-id: 200
                } 
            }
        direction: right
        **.style.border-radius: 99
        
pandas -> certx.vis.nb
sympy -> certx.operation.sp
networkx -> certx.cg
certx.operation.sp -> certx.se
typing -> certx.vis.nb
typing -> certx.cg
certx.parser.equations -> certx.se
pprint -> certx.cg
sympy -> certx.se
re -> certx.utils
io -> certx.vis.nx
certx.operation.nx -> certx.cg
networkx -> certx.vis.nx
networkx -> certx.operation.nx
IPython -> certx.vis.nb
certx.vis.nb -> certx.cg
certx.utils -> certx.se
pprint -> certx.parser.equations
numpy -> certx.vis.nx
argparse -> certx.operation.nx
pandas -> certx.operation.sp
matplotlib -> certx.vis.nx
certx.utils -> certx.operation.sp
certx.utils -> certx.vis.nx
argparse -> certx.parser.graph
pandas -> certx.operation.nx
igraph -> certx.vis.nx
itertools -> certx.parser.graph
pprint -> certx.parser.graph
certx.vis.nx -> certx.cg
certx.parser.graph -> certx.cg
pprint -> certx.se
typing -> certx.vis.nx
*.utils: null
re: null
io: null
itertools: null
argparse: null
IPython: null
pprint: null